@startuml
title Class diagram of \n<font name=monospace><color #5132be>Break6</color></font> class

class Break6 {
    {method} + {static} main(String[] args): void
}
note bottom of Break6
    file: Break6.java
    
    Where you put a 
    label is important.
end note
@enduml