@startuml
title Class diagram of \n<font name=monospace><color #5132be>Break5</color></font> class

class Break5 {
    {method} + {static} main(String[] args): void
}
note bottom of Break5
    file: Break5.java
    
    Another example of 
    using break with a label.
end note
@enduml