@startuml
title Class diagram of \n<font name=monospace><color #5132be>DecrFor</color></font> class

class DecrFor {
    {method} + {static} main(String[] args): void
}
note bottom of DecrFor
    file: DecrFor.java
    
    A negatively running 
    for loop.
end note
@enduml