@startuml
title Class diagram of \n<font name=monospace><color #5132be>Empty2</color></font> class

class Empty2 {
    {method} + {static} main(String[] args): void
}
note bottom of Empty2
    file: Empty2.java
    
    Parts of the for can 
    be empty (initialization).
end note
@enduml