@startuml
title Class diagram of \n<font name=monospace><color #5132be>ForVar</color></font> class

class ForVar {
    {method} + {static} main(String[] args): void
}
note bottom of ForVar
    file: ForVar.java
    
    Declare loop control 
    variable inside the for.
end note
@enduml