@startuml
title Class diagram of \n<font name=monospace><color #5132be>Guess</color></font> class


class Guess {
    
}
note bottom of Guess
    file: Guess.java
    
    Guess the letter game.
end note
@enduml