@startuml
title Class diagram of \n<font name=monospace><color #5132be>Guess3</color></font> class

class Guess3 {
    {method} + {static} main(String[] args): void
}
note bottom of Guess3
    file: Guess3.java
    
    Guess the letter 
    game. Version 3.
end note
@enduml