@startuml
title Class diagram of \n<font name=monospace><color #5132be>Guess4</color></font> class

class Guess4 {
    {method} + {static} main(String[] args): void
}
note bottom of Guess4
    file: Guess4.java
    
    Guess the letter 
    game. Version 4.
end note
@enduml