@startuml
title Class diagram of \n<font name=monospace><color #5132be>Ladder</color></font> class

class Ladder {
    
}
note bottom of Ladder
    file: Ladder.java
    
    Demonstrate and 
    if-else-if ladder.
end note
@enduml