@startuml
<style>
    Activity {
        FontSize 12
        diamond {
            LineColor yellow
            BackgroundColor burlywood
            FontSize 14
            FontStyle bold
        }
    }
</style>
title Activity diagram of \nBlockDemo.main() method

start

:double i, j, d;;
note : Comma separated \nmultiple variable \ndeclaration

:i = 5;; <<task>>
:j = 10;; <<task>>

if(i != 0) then (<color:green>true)
    :System.out.println("i does not equal zero");; <<output>>
    :d = j / i;; <<task>>
    :System.out.println("j / i is " + d);; <<output>>
endif
note : the target of this \nif is a block

stop

@enduml