@startuml
title Class diagram of \n<font name=monospace><color #5132be>JBG_HS_Ch02_SelfTest_10</color></font> class

class JBG_HS_Ch02_SelfTest_10 {
    {method} + {static} main(String[] args): void
}
note bottom of JBG_HS_Ch02_SelfTest_10
    file: JBG_HS_Ch02_SelfTest_10.java
    
    Find all of the prime 
    numbers between 2 and 100.
end note
@enduml