@startuml
title Class diagram of \n<font name=monospace><color #5132be>SCops</color></font> class

class SCops {
    {method} + {static} main(String[] args): void
}
note bottom of SCops
    file: SCops.java
    
    Demonstrate the 
    short-circuit operators.
end note
@enduml